### ISSUE TITLE
the extension is not ready for contao 3.5

### ISSUE THREAD

**Issue by Telepathnic** [menatwork-ia/rootsearch#3]
the extension is not displayed in the extension catalog in contao 3.5.

**Comment by stefanheimes** [comment]
No  prob on Contao 3.5.12. Do you use the ER or Composer version ?

**Comment by Telepathnic** [comment]
No Composer can´t use it by my Provider.

Mit freundlichen Grüßen
Benjamin Bajic

---

Webentwicklung

Anton Gerl GmbH
Industriestraße 131 d
D 50996 Köln

Tel. +49 0221-80109296
Fax +49 0221-80109299
b.bajic@gerl-dental.de
http://gerl-dental.de/

Amtsgericht Köln, HRB 10129  ●  Ust.-Id-Nr.: DE 123471701 Geschäftsführer: Dipl.-Kfm. Rainer Göbel, Michael Wulff, Dipl. Jur. Hillar Schuh,
Dipl.-Kfm. Jürgen Richter, Dipl.-Kfm./MBA Henning Richter

Von: Stefan Heimes [mailto:notifications@github.com]
Gesendet: Montag, 2. Mai 2016 15:32
An: menatwork-ia/rootsearch rootsearch@noreply.github.com
Cc: Bajic, Benjamin B.Bajic@gerl-dental.de; Author author@noreply.github.com
Betreff: Re: [menatwork-ia/rootsearch] the extension is not ready for contao 3.5 (#3)

No prob on Contao 3.5.12. Do you use the ER or Composer version ?
