### ISSUE TITLE
Compatibility with Contao 4

### ISSUE THREAD

**Issue by ghost** [menatwork-ia/rootsearch#5]
Will this extension be updated to work with Contao 4.4 LTS? If not, I would fork it, if convenient.

**Comment by fritzmg** [comment]
Have you tested the extension in Contao 4?

**Comment by ghost** [comment]
I am pretty sure we did test it. The project was some time back, so I could be mistaken. But if I remember correctly the site is running Contao 4.4 and the rootsearch stuff works. Not sure whether we modified it for that.

**Comment by fritzmg** [comment]
Well if you can definitely confirm that it works you could make a PR with for an updated `composer.json`:
```diff
-		"contao/core":">=3,<4",
-		"contao-community-alliance/composer-installer":"*"
+		"contao/core-bundle":"^3.0|^4.0",
+		"contao-community-alliance/composer-plugin":"^2.4|^3.0"
```
